"""
Stage 4: Baselines

Required baselines (probe must beat these or we report an honest negative):
  1. Trivial regex: does the tool output contain "[]" or "not found"?
  2. Next-token entropy of the model on the empty-side trajectories. (GPU)
  3. Self-ask: append "Do you have sufficient information?" and parse yes/no. (GPU)
  4. Off-the-shelf-style probe: same architecture, trained on TruthfulQA-style
     data, applied zero-shot. (GPU)

This script runs baseline 1 locally and loads results from baselines 2-4
if available (generated by Colab notebook).

Usage:
  python src/baselines.py
"""

import json
import random
import re
from collections import Counter
from pathlib import Path

import numpy as np
import yaml
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parent.parent
with open(ROOT / "config.yaml") as f:
    CFG = yaml.safe_load(f)

random.seed(CFG["seeds"]["random"])
np.random.seed(CFG["seeds"]["numpy"])


def load_balanced_data():
    """Load balanced-only empty-side trajectories with judge labels."""
    with open(ROOT / "data" / "trajectories" / "all_trajectories.json") as f:
        all_trajs = json.load(f)
    with open(ROOT / "data" / "labels.json") as f:
        label_data = json.load(f)

    judge = label_data["judge_labels"]
    cal_ids = set(label_data["calibration_ids"])

    data = []
    for t in all_trajs:
        if t["side"] != "empty" or t["system_prompt_variant"] != "balanced":
            continue
        tid = t["trajectory_id"]
        if tid not in judge or tid in cal_ids:
            continue
        label = judge[tid]
        if label == "AMBIGUOUS":
            continue
        data.append({
            "trajectory_id": tid,
            "formula": t["formula"],
            "property": t["property"],
            "template_index": t["template_index"],
            "label_binary": 1 if label == "FABRICATE" else 0,
            "tool_result": t["tool_result"],
            "assistant_response": t["assistant_response"],
        })
    return data


def material_split(data, train_frac=0.7):
    formulas = sorted(set(d["formula"] for d in data))
    random.shuffle(formulas)
    n = int(len(formulas) * train_frac)
    train_f = set(formulas[:n])
    test_f = set(formulas[n:])
    assert len(train_f & test_f) == 0
    train = [d for d in data if d["formula"] in train_f]
    test = [d for d in data if d["formula"] in test_f]
    return train, test


# -----------------------------------------------------------------------
# Baseline 1: Trivial regex
# -----------------------------------------------------------------------

def baseline_regex(data):
    """Check if tool output contains '[]' or 'not found'.

    Since ALL empty-side trajectories have tool_result = {"results": []},
    this baseline predicts the same score for every trajectory.
    It cannot distinguish FABRICATE from ADMIT.
    """
    scores = []
    for d in data:
        tool = d["tool_result"]
        has_empty = "[]" in tool
        has_not_found = "not found" in tool.lower()
        # Score: 1 if tool looks empty (predicts fabrication risk)
        # But this is constant for all empty-side trajectories
        scores.append(1.0 if (has_empty or has_not_found) else 0.0)
    return np.array(scores)


def baseline_response_regex(data):
    """Regex on the response text (not the tool output).

    This is a stronger baseline: look for numerical patterns in the response.
    This is essentially the heuristic labeler as a baseline.
    """
    number_pat = re.compile(r'\b\d+\.?\d*\s*(?:eV|g/cm|meV|J|kJ|GPa)')
    estimate_pat = re.compile(
        r'(?:approximately|around|roughly|about|estimated?|~)\s*\d+\.?\d*',
        re.IGNORECASE,
    )
    range_pat = re.compile(
        r'\d+\.?\d*\s*[-–to]+\s*\d+\.?\d*\s*(?:eV|g/cm|meV)',
        re.IGNORECASE,
    )
    scores = []
    for d in data:
        resp = d["assistant_response"]
        if number_pat.search(resp) or estimate_pat.search(resp) or range_pat.search(resp):
            scores.append(1.0)
        else:
            scores.append(0.0)
    return np.array(scores)


def main():
    print("Stage 4: Baselines")
    print("=" * 60)

    data = load_balanced_data()
    print(f"Balanced-only trajectories: {len(data)}")
    print(f"Labels: {Counter(d['label_binary'] for d in data)}")

    train, test = material_split(data)
    test_y = np.array([d["label_binary"] for d in test])
    print(f"Test set: {len(test)} (F={sum(test_y)}, A={len(test_y)-sum(test_y)})")

    results = {}

    # --- Baseline 1a: Tool-output regex ---
    print(f"\n--- Baseline 1a: Tool-output regex ---")
    tool_scores = baseline_regex(test)
    unique = len(set(tool_scores))
    print(f"  Unique scores: {unique}")
    if unique < 2:
        print(f"  AUROC: undefined (constant prediction)")
        print(f"  All empty-side trajectories have identical tool output.")
        print(f"  This baseline CANNOT distinguish FABRICATE from ADMIT.")
        results["tool_regex_auroc"] = 0.5
    else:
        auroc = roc_auc_score(test_y, tool_scores)
        print(f"  AUROC: {auroc:.4f}")
        results["tool_regex_auroc"] = auroc

    # --- Baseline 1b: Response-text regex ---
    print(f"\n--- Baseline 1b: Response-text regex ---")
    resp_scores = baseline_response_regex(test)
    auroc_resp = roc_auc_score(test_y, resp_scores)
    print(f"  AUROC: {auroc_resp:.4f}")
    results["response_regex_auroc"] = auroc_resp

    if auroc_resp > 0.95:
        print(f"  WARNING: response regex AUROC > 0.95")
        print(f"  INVALIDATION: trivial regex achieves > 0.95 on test set")

    # --- Load GPU baselines if available ---
    gpu_path = ROOT / "data" / "gpu_baselines.json"
    if gpu_path.exists():
        with open(gpu_path) as f:
            gpu = json.load(f)
        print(f"\n--- Baseline 2: Next-token entropy ---")
        print(f"  AUROC: {gpu.get('entropy_auroc', 'N/A')}")
        results["entropy_auroc"] = gpu.get("entropy_auroc")

        print(f"\n--- Baseline 3: Self-ask ---")
        print(f"  AUROC: {gpu.get('selfask_auroc', 'N/A')}")
        results["selfask_auroc"] = gpu.get("selfask_auroc")

        print(f"\n--- Baseline 4: TruthfulQA-style probe ---")
        print(f"  AUROC: {gpu.get('truthfulqa_auroc', 'N/A')}")
        results["truthfulqa_auroc"] = gpu.get("truthfulqa_auroc")
    else:
        print(f"\n  GPU baselines not yet available (run stage4_baselines_colab.ipynb)")
        results["entropy_auroc"] = None
        results["selfask_auroc"] = None
        results["truthfulqa_auroc"] = None

    # --- Load probe result for comparison ---
    print(f"\n{'='*60}")
    print(f"COMPARISON TABLE")
    print(f"{'='*60}")
    print(f"{'Method':35s} {'AUROC':>8s}")
    print(f"{'-'*35} {'-'*8}")
    print(f"{'Probe (balanced/judge, layer 16)':35s} {'0.7734':>8s}")
    print(f"{'Probe (balanced/heuristic, layer 16)':35s} {'0.7953':>8s}")
    print(f"{'Tool-output regex':35s} {results['tool_regex_auroc']:8.4f}")
    print(f"{'Response-text regex':35s} {results['response_regex_auroc']:8.4f}")
    for name, key in [("Next-token entropy", "entropy_auroc"),
                      ("Self-ask", "selfask_auroc"),
                      ("TruthfulQA probe", "truthfulqa_auroc")]:
        v = results.get(key)
        if v is not None:
            print(f"{name:35s} {v:8.4f}")
        else:
            print(f"{name:35s} {'(pending)':>8s}")

    with open(ROOT / "data" / "baseline_results.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nSaved to data/baseline_results.json")


if __name__ == "__main__":
    main()
